source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ios-sdk_Example', :exclusive => true do
  pod 'ios-sdk', :path => '../'
end

target 'ios-sdk_Tests', :exclusive => true do
  pod 'ios-sdk', :path => '../'

  
end
