source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/romair/CocoaPodsSpec.git'

use_frameworks!

pod 'SwiftyTraverson', '0.0.0-SNAPSHOT'

target 'ios-sdk_Example' do
  pod 'SmoopeSDK', :path => '../'
end

target 'ios-sdk_Tests' do
  pod 'SmoopeSDK', :path => '../'

  pod 'SwiftyJSON', '~> 2.3' 
end
