language: objective-c

cache: cocoapods
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.0

before_install:
- rvm install 2.1.5
- gem install cocoapods
- pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild test -workspace Example/ios-sdk.xcworkspace -scheme ios-sdk-Tests -destination "platform=iOS Simulator,name=iPhone 6" | xcpretty
- pod lib lint --sources='https://github.com/CocoaPods/Specs,https://github.com/romair/CocoaPodsSpec.git' --allow-warnings
