language: objective-c

osx_image: xcode7.1

before_install:
- rvm install 2.1.5
- gem install cocoapods
- pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild test -workspace Example/ios-sdk.xcworkspace -scheme ios-sdk-Example -sdk iphonesimulator8.1 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
